pub const ENV_WVM_PRUNE: &str = "ENV_WVM_PRUNE";
pub const ENV_WVM_RUN_EXEX: &str = "ENV_WVM_RUN_EXEX";

pub const ENV_WVM_SEQUENCER_ADDRESS: &str = "ENV_WVM_SEQUENCER_ADDRESS";

pub const ENV_WVM_LAMBDA_ENDPOINT: &str = "ENV_WVM_LAMBDA_ENDPOINT";
